# Generated by Django 4.2.7 on 2023-11-29 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='fristname',
            new_name='firstname',
        ),
    ]
